<?php
/**
 * Template tags: icons and components.
 *
 * @package Torrehub
 */

defined( 'ABSPATH' ) || exit;

/**
 * Versioned URL of the icon sprite.
 */
function th_sprite_url(): string {
	return add_query_arg( 'v', th_asset_version( 'assets/icons/sprite.svg' ), th_asset( 'assets/icons/sprite.svg' ) );
}

/**
 * Names available in the sprite (assets/icons/icons.json, generated by _dev/tools/build-sprite.mjs).
 *
 * @return array<int,string>
 */
function th_icon_names(): array {
	static $names = null;
	if ( null === $names ) {
		$json  = file_get_contents( TH_DIR . '/assets/icons/icons.json' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		$names = $json ? (array) json_decode( $json, true ) : array();
	}
	return $names;
}

/**
 * Inline SVG icon from the sprite.
 *
 * @param string                                       $name Icon name (see icons.json), e.g. 'search', 'cat-services'.
 * @param array{size?:int,class?:string,label?:string} $args  label → announced to screen readers; otherwise decorative.
 */
function th_get_icon( string $name, array $args = array() ): string {
	if ( ! in_array( $name, th_icon_names(), true ) ) {
		if ( WP_DEBUG ) {
			trigger_error( esc_html( "th_icon: unknown icon '{$name}'" ), E_USER_NOTICE ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_trigger_error
		}
		return '';
	}
	$size  = (int) ( $args['size'] ?? 20 );
	$label = (string) ( $args['label'] ?? '' );

	$attrs = array(
		'class'       => th_classes( 'th-icon', 'th-icon--' . $name, (string) ( $args['class'] ?? '' ) ),
		'width'       => $size,
		'height'      => $size,
		'focusable'   => 'false',
		'aria-hidden' => '' === $label ? 'true' : null,
		'role'        => '' === $label ? null : 'img',
		'aria-label'  => '' === $label ? null : $label,
	);

	return sprintf( '<svg%s><use href="%s#i-%s"></use></svg>', th_attrs( $attrs ), esc_url( th_sprite_url() ), esc_attr( $name ) );
}

/**
 * Echo an icon (see th_get_icon()).
 *
 * @param string                                       $name Icon name.
 * @param array{size?:int,class?:string,label?:string} $args Icon options.
 */
function th_icon( string $name, array $args = array() ): void {
	echo th_get_icon( $name, $args ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- built from escaped parts.
}

/**
 * Render a component partial: template-parts/components/<name>.php with $args.
 *
 * @param string              $name Component name.
 * @param array<string,mixed> $args Component arguments (documented at the top of each partial).
 */
function th_component( string $name, array $args = array() ): void {
	get_template_part( 'template-parts/components/' . $name, null, $args );
}

/**
 * Same as th_component() but returns the markup.
 *
 * @param string              $name Component name.
 * @param array<string,mixed> $args Component arguments.
 */
function th_get_component( string $name, array $args = array() ): string {
	ob_start();
	th_component( $name, $args );
	return (string) ob_get_clean();
}

/**
 * User avatar: RTCL profile photo (`_rtcl_pp_id`) or initials. DECISION: no Gravatar (external request, privacy).
 *
 * @param int $user_id User id.
 * @param int $size    CSS pixel size.
 */
function th_get_avatar( int $user_id, int $size = 38 ): string {
	$user = get_userdata( $user_id );
	if ( ! $user ) {
		return '';
	}
	$photo = (int) get_user_meta( $user_id, '_rtcl_pp_id', true );
	if ( $photo && wp_attachment_is_image( $photo ) ) {
		return wp_get_attachment_image(
			$photo,
			array( $size * 2, $size * 2 ),
			false,
			array(
				'class'   => 'th-avatar',
				'alt'     => '',
				'width'   => $size,
				'height'  => $size,
				'loading' => 'lazy',
			)
		);
	}
	$name     = trim( $user->first_name . ' ' . $user->last_name );
	$name     = '' !== $name ? $name : $user->display_name;
	$parts    = preg_split( '/\s+/u', $name );
	$initials = mb_strtoupper( mb_substr( (string) ( $parts[0] ?? '' ), 0, 1 ) . mb_substr( (string) ( $parts[1] ?? '' ), 0, 1 ) );
	return sprintf( '<span class="th-avatar th-avatar--initials" style="--th-avatar-size:%dpx" aria-hidden="true">%s</span>', $size, esc_html( $initials ? $initials : '?' ) );
}
